--- #YAML:1.0
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
name: Modern-Open
version: 0.09
abstract: Autovivification, Autodie, and 3-args open support
author:
  - ina <ina@cpan.org>
license: perl
generated_by: pmake.bat
requires:
  Archive::Tar: 0.072
  Compress::Zlib: 1.03
  Config: 0
  ExtUtils::MakeMaker: 5.4302
  Fcntl: 1.03
  File::Basename: 2.6
  File::Copy: 2.02
  File::Path: 1.0401
  FindBin: 1.42
  Getopt::Std: 1.01
  perl: 5.005_03
  strict: 1.01
build_requires:
  Test: 1.122
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/ina-cpan/Modern-Open
